Steps:

1. Select Kernel
2. Install Extensions
3. Select 'base' kerner

In [2]:
print("hello")

hello

In [3]:
import pandas as pd

In [4]:
# Loading in the csv files
books = pd.read_csv("data/03_Library Systembook.csv")
customers = pd.read_csv("data/03_Library SystemCustomers.csv")

In [5]:
books.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

In [6]:
customers.head()

   Customer ID   Customer Name
0          1.0        Jane Doe
1          2.0      John Smith
2          3.0      Dan Reeves
3          NaN             NaN
4          5.0  William Holden

In [7]:
# Dropping NA Values in Customers
customers.dropna(inplace=True)
customers.head()

   Customer ID   Customer Name
0          1.0        Jane Doe
1          2.0      John Smith
2          3.0      Dan Reeves
4          5.0  William Holden
5          6.0   Jaztyn Forest

Starting Points:

1. Get rid of the speech marks in Book checkout.
2. Convert or "map" 2 weeks in the days allowed to borrow col to an integer value. 
3. Stretch: Try to convert the date columns into datetime.

In [8]:
books.head(n=20)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0
5,6.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
6,7.0,IT,"""10/04/2063""",03/04/2023,2 weeks,6.0
7,8.0,Misery,"""15/04/2023""",03/04/2023,2 weeks,7.0
8,9.0,Catch 22,"""15/04/2023""",16/04/2023,2 weeks,7.0
9,10.0,Animal Farm,"""20/04/2023""",24/04/2023,2 weeks,2.0
10,11.0,1984,"""23/04/2023""",27/04/2023,2 weeks,8.0
11,12.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
12,13.0,East of Eden,"""30/04/2023""",05/05/2023,2 weeks,2.0
13,14.0,America Is in the Heart,"""01/05/2023""",07/05/2023,2 weeks,3.0
14,15.0,Wuthering Heights,"""01/05/2023""",10/05/2023,2 weeks,9.0
15,16.0,Dark Tales,"""15/05/2023""",01/06/2023,2 weeks,2.0
16,17.0,The Bloody Chamber,"""32/05/2023""",04/06/2023,2 weeks,3.0
17,18.0,Les Miserables,"""03/06/2023""",07/06/2023,2 weeks,5.0
18,19.0,Dracula,"""10/06/2023""",10/07/2023,2 weeks,10.0
19,20.0,Frankenstein,"""01/06/2023""",20/06/2023,2 weeks,2.0